export const CLEAR_FETCH_ENTITY_STATUS = 'CLEAR_FETCH_ENTITY_STATUS'
export const FETCH_CUSTOM_DICT = 'FETCH_CUSTOM_DICT'

export const FETCH_NOTICES = 'FETCH_NOTICES'
export const FETCH_NOTICES_REQUESTED = 'FETCH_NOTICES_REQUESTED'
export const FETCH_NOTICES_SUCCESS = 'FETCH_NOTICES_SUCCESS'
export const FETCH_NOTICES_FAILED = 'FETCH_NOTICES_FAILED'

export const FETCH_SINGLE_NOTICE = 'FETCH_SINGLE_NOTICE'
export const FETCH_SINGLE_NOTICE_REQUESTED = 'FETCH_SINGLE_NOTICE_REQUESTED'
export const FETCH_SINGLE_NOTICE_SUCCESS = 'FETCH_SINGLE_NOTICE_SUCCESS'
export const FETCH_SINGLE_NOTICE_FAILED = 'FETCH_SINGLE_NOTICE_FAILED'
export const SET_NEW_NOTICE_REQUESTED = 'SET_NEW_NOTICE_REQUESTED'
export const SET_NEW_NOTICE = 'SET_NEW_NOTICE'

export const FETCH_COMMISSIONS = 'FETCH_COMMISSIONS'
export const FETCH_COMMISSIONS_REQUESTED = 'FETCH_COMMISSIONS_REQUESTED'
export const FETCH_COMMISSIONS_SUCCESS = 'FETCH_COMMISSIONS_SUCCESS'
export const FETCH_COMMISSIONS_FAILED = 'FETCH_COMMISSIONS_FAILED'

export const FETCH_SINGLE_COMMISSION = 'FETCH_SINGLE_COMMISSION'
export const FETCH_SINGLE_COMMISSION_REQUESTED = 'FETCH_SINGLE_COMMISSION_REQUESTED'
export const FETCH_SINGLE_COMMISSION_SUCCESS = 'FETCH_SINGLE_COMMISSION_SUCCESS'
export const FETCH_SINGLE_COMMISSION_FAILED = 'FETCH_SINGLE_COMMISSION_FAILED'
export const SET_NEW_COMMISSION_REQUESTED = 'SET_NEW_COMMISSION_REQUESTED'
export const SET_NEW_COMMISSION = 'COMMISSION'

export const FIND_PERSON_BY_IIN = 'FIND_PERSON_BY_IIN'
export const FIND_PERSON_BY_IIN_REQUESTED = 'FIND_PERSON_BY_IIN_REQUESTED'
export const FIND_PERSON_BY_IIN_SUCCESS = 'FIND_PERSON_BY_IIN_SUCCESS'
export const FIND_PERSON_BY_IIN_FAILED = 'FIND_PERSON_BY_IIN_FAILED'

export const FETCH_COMMISSION_MEMBERS = 'FETCH_COMMISSION_MEMBERS'
export const FETCH_COMMISSION_MEMBERS_REQUESTED = 'FETCH_COMMISSION_MEMBERS_REQUESTED'
export const FETCH_COMMISSION_MEMBERS_SUCCESS = 'FETCH_COMMISSION_MEMBERS_SUCCESS'
export const FETCH_COMMISSION_MEMBERS_FAILED = 'FETCH_COMMISSION_MEMBERS_FAILED'

export const FETCH_SINGLE_COMMISSION_MEMBER = 'FETCH_SINGLE_COMMISSION_MEMBER'
export const FETCH_SINGLE_COMMISSION_MEMBER_REQUESTED = 'FETCH_SINGLE_COMMISSION_MEMBER_REQUESTED'
export const FETCH_SINGLE_COMMISSION_MEMBER_SUCCESS = 'FETCH_SINGLE_COMMISSION_MEMBER_SUCCESS'
export const FETCH_SINGLE_COMMISSION_MEMBER_FAILED = 'FETCH_SINGLE_COMMISSION_MEMBER_FAILED'

export const DELETE_COMMISSION_MEMBER = 'DELETE_COMMISSION_MEMBER'
export const DELETE_COMMISSION_MEMBER_SUCCESS = 'DELETE_COMMISSION_MEMBER_SUCCESS'
export const DELETE_COMMISSION_MEMBER_FAILED = 'DELETE_COMMISSION_MEMBER_FAILED'

export const FETCH_ADVERTISEMENT_APPLICANTS = 'FETCH_ADVERTISEMENT_APPLICANTS'
export const FETCH_ADVERTISEMENT_APPLICANTS_REQUESTED = 'FETCH_ADVERTISEMENT_APPLICANTS_REQUESTED'
export const FETCH_ADVERTISEMENT_APPLICANTS_SUCCESS = 'FETCH_ADVERTISEMENT_APPLICANTS_SUCCESS'
export const FETCH_ADVERTISEMENT_APPLICANTS_FAILED = 'FETCH_ADVERTISEMENT_APPLICANTS_FAILED'

export const FETCH_SUPPLIERS = 'FETCH_SUPPLIERS'
export const FETCH_SUPPLIERS_REQUESTED = 'FETCH_SUPPLIERS_REQUESTED'
export const FETCH_SUPPLIERS_SUCCESS = 'FETCH_SUPPLIERS_SUCCESS'
export const FETCH_SUPPLIERS_FAILED = 'FETCH_SUPPLIERS_FAILED'

export const FETCH_BAD_SUPPLIERS = 'FETCH_BAD_SUPPLIERS'
export const FETCH_BAD_SUPPLIERS_REQUESTED = 'FETCH_BAD_SUPPLIERS_REQUESTED'
export const FETCH_BAD_SUPPLIERS_SUCCESS = 'FETCH_BAD_SUPPLIERS_SUCCESS'
export const FETCH_BAD_SUPPLIERS_FAILED = 'FETCH_BAD_SUPPLIERS_FAILED'

export enum FETCH_ENTITY_STATUS {
  IDLE,
  FETCHING,
  SUCCESS,
  FAILED,
}
